### ISSUE TITLE
[QTVY-132] 회원탈퇴, 비밀번호 재설정 구현

### ISSUE THREAD

**Issue by seon022** [prgrms-web-devcourse-final-project/WEB1_2_PublicPlus_FE#110]
### 🎟️ 상위 작업 (Ticket Number)

QTVY-20

### 🌳 브랜치명 (Branch)

user-management

### 📝 상세 내용(Description)

회원탈퇴, 비밀번호 재설정 ui 구현 및 api 연동

### ✅ 체크리스트(Tasks)

- [x] 비밀번호 재설정 구현
- [x] 회원탈퇴 구현

**Comment by sssssubin** [comment]
Jira Issue Created: [QTVY-132](https://rlaqudwn123456.atlassian.net/browse/QTVY-132)

[QTVY-132]: https://rlaqudwn123456.atlassian.net/browse/QTVY-132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
