### ISSUE TITLE
[QTVY-142] 회원가입, 소셜로그인 통합 테스트

### ISSUE THREAD

**Issue by seon022** [prgrms-web-devcourse-final-project/WEB1_2_PublicPlus_FE#118]
### 🎟️ 상위 작업 (Ticket Number)

QTVY-135

### 🌳 브랜치명 (Branch)

auth-api-intergration

### 📝 상세 내용(Description)

회원가입, 소셜로그인 api 연동 및 통합 테스트

### ✅ 체크리스트(Tasks)

- [ ] 회원가입
- [ ] 소셜로그인

**Comment by sssssubin** [comment]
Jira Issue Created: [QTVY-142](https://rlaqudwn123456.atlassian.net/browse/QTVY-142)

[QTVY-142]: https://rlaqudwn123456.atlassian.net/browse/QTVY-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
