### ISSUE TITLE
[QTVY-107] 채팅 UI 구현

### ISSUE THREAD

**Issue by seon022** [prgrms-web-devcourse-final-project/WEB1_2_PublicPlus_FE#46]
### 🎟️ 상위 작업 (Ticket Number)

QTVY-23

### 🌳 브랜치명 (Branch)

chat-ui

### 📝 상세 내용(Description)

채팅 UI 구현

### ✅ 체크리스트(Tasks)

- [x] 채팅 목록 UI
- [x] 채팅방 UI

**Comment by sssssubin** [comment]
Jira Issue Created: [QTVY-107](https://rlaqudwn123456.atlassian.net/browse/QTVY-107)

[QTVY-107]: https://rlaqudwn123456.atlassian.net/browse/QTVY-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
