### ISSUE TITLE
[QTVY-110] Swagger문서 기반 openapi-generator 동기화

### ISSUE THREAD

**Issue by seon022** [prgrms-web-devcourse-final-project/WEB1_2_PublicPlus_FE#48]
### 🎟️ 상위 작업 (Ticket Number)

QTVY-109

### 🌳 브랜치명 (Branch)

swagger-update

### 📝 상세 내용(Description)

openapi-generator Swagger문서 업데이트

### ✅ 체크리스트(Tasks)

- [x] Swagger문서 업데이트 , openapi-generator 실행

**Comment by sssssubin** [comment]
Jira Issue Created: [QTVY-110](https://rlaqudwn123456.atlassian.net/browse/QTVY-110)

[QTVY-110]: https://rlaqudwn123456.atlassian.net/browse/QTVY-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
