### ISSUE TITLE
[QTVY-113] 로그인, 회원가입 msw 연동 테스트

### ISSUE THREAD

**Issue by seon022** [prgrms-web-devcourse-final-project/WEB1_2_PublicPlus_FE#55]
### 🎟️ 상위 작업 (Ticket Number)

QTVY-20

### 🌳 브랜치명 (Branch)

auth-msw-test

### 📝 상세 내용(Description)

로그인, 회원가입 msw-auth-integration

### ✅ 체크리스트(Tasks)

- [x] 로그인, 회원가입 msw-auth-integration
- [x] 로그아웃

**Comment by sssssubin** [comment]
Jira Issue Created: [QTVY-113](https://rlaqudwn123456.atlassian.net/browse/QTVY-113)

[QTVY-113]: https://rlaqudwn123456.atlassian.net/browse/QTVY-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
